In [ ]:
import numpy as np
import random


def matrix_generate(N):
    L = np.matrix(np.diag([random.uniform(1,100) for i in range(N)]))
    C = np.matrix(np.random.rand(N,N))

    A = np.linalg.inv(C) * L * C

    return A

def H(a): #hessenberg
    n = len(a)
    for i in range(n):
        for j in range(n):
            if i - j > 1 and a[i][j] != 0:
                k = a[i][j] / a[j + 1][j]

                for u in range(n):
                    a[j + 1][u] = a[j + 1][u] * k
                    a[i][u] -= a[j + 1][u]
    return(a)


def helper(mu):
    k = 0
    summ = 0
    for i in range(len(mu)):
        if abs(mu[i]) > 10**(-8):
            summ+=mu[i]
            k+=1
    return summ / k if k!= 0 else 0

def PM_method(A):
    N = len(A)
    eps = 10**(-6)
    delta = 10**(-8)
    lambda_0 = [0]*N
    lambda_1 = [0]*N
    A = [[1, -2, -2], [1, 4, 2], [0, -6, -4]]
    A = np.matrix(A)
    y0 = np.matrix([[random.randint(1,100)] for i in range(N)]) # создаем начальный вектор y0
    z = y0 / np.linalg.norm(y0) # нормируем

    while True:

        y_next = A * z
        z = y_next / np.linalg.norm(y_next)

        for i in range(N):
            if abs(z[i]) > delta:
                lambda_1[i] =  y_next[i][0] / z[i][0]

            else:
                lambda_1[i] = lambda_0[i]

        checker = True
        for i in range(N):
            if abs(lambda_1[i] - lambda_0[i]) > eps:
                checker = False

        if checker:
            break

        else:
            lambda_0 = lambda_1.copy()

    eigenvalue = 0
    k=0
    for i in range(N):
        if lambda_1[i] != lambda_0[i]:
            eigenvalue += lambda_1[i]
            k+=1

    print(eigenvalue/k, 'eigenvalue')
    print(z, 'eigenvector')



def reverse_PM(A, sigmas):
    N = len(A)
    eps = 10 ** (-3)
    d = 10**(-6)
    for sigma0 in sigmas:
        y0 = np.matrix([[random.randint(1, 100)] for i in range(N)])  # создаем начальный вектор y0
        z0 = y0 / np.linalg.norm(y0)
        # A = [[1, -2, -2], [1, 4, 2], [0, -6, -4]]
        # A = np.matrix(A)

        mu = [0] * N



        while True:
            y1 = np.linalg.inv(A - sigma0*(np.matrix(np.eye(N))))*z0
            Z0 = np.array(z0)
            y1 = np.array(y1)
            z0 = y1 / np.linalg.norm(y1)

            for i in range(N):
                if abs(y1[i][0]) > d:
                    mu[i] =  Z0[i][0]/y1[i][0]
                else:
                    mu[i] = 0

            sigma1 = sigma0 + helper(mu)

            checker = True
            for i in range(N):
                if abs(z0[i][0] - Z0[i][0]) > 10**(-2):
                    checker = False

            if abs(sigma1 - sigma0) < 10**(-2) and checker:
                break

            sigma0 = sigma1.copy()
        print(sigma1, '\n', z0, f'eigenvalue + eigenvector, sigma:{sigma0}')


def QR_method(A):
    N = len(A)
    e = 10*(-3)
    # A = [[1, -2, -2], [1, 4, 2], [0, -6, -4]]
    # A = np.matrix(A)

    A = np.array(A)
    A = H(A)
    A = np.matrix(A)
    print(np.linalg.eig(A)[0], 'real eigenvalues',
          np.linalg.eig(A)[1], 'real eigenvectors')

    for i in range(1,90):
        a = np.array(A)
        Q, R = np.linalg.qr(A - a[len(a)-1][len(a)-1] * np.eye(len(a)))
        Q = np.matrix(Q)
        R = np.matrix(R)


        A = R*Q + a[len(a)-1][len(a)-1]*np.eye(len(a))
        a1 = np.array(A)
        if abs(a1[len(a1)-1][len(a1)-1] - a[len(a)-1][len(a)-1]) < 0.001*abs(a[len(a)-1][len(a)-1]):

            print(a1[len(a1)-1][len(a1)-1], 'found eigenvalue')

            if len(a1) - 1 == 1:
                print(a1[len(a1)-2][len(a1)-2], 'found eigenvalue')
                break

            A_new = [[0]*(len(A)-1) for i in range(len(A)-1)]
            for j in range(len(A_new)):
                for k in range(len(A_new)):
                    A_new[j][k] = a1[j][k]

            A = np.matrix(A_new.copy())
    pass


In [ ]:
N = 3
#AA = matrix_generate(N)
AA = [
AA = np.matrix(AA)
print(AA)
print('-'*10)
PM_method(AA)
print('-'*10)
reverse_PM(AA, [0.1, 1.1, 1.8])
print('-'*10)
QR_method(AA)


[[2 0 0]]
----------
----------
----------


LinAlgError: ignored

In [ ]:
QR_method(3)

[ 2.00000000e+00  4.79260728e-15 -1.00000000e+00] корни
-1.0000009151380542 собственное число
9.137034963419397e-07 собственное число
2.000000001434561 собственное число


In [ ]:
import random
import numpy as np
import math


n = 3
h = []
c = []
for i in range(n):
	b = [0] * n
	b[i] = random.randint(1, 101)
	h.append(b)
	b = []
	for j in range(n):
		b.append(random.randint(1, 101))
	c.append(b)
print(h)
a = np.dot(np.dot(np.linalg.inv(c), h), c)
print(a)
a = [[1, -2, -2], [1, 4, 2], [0, -6, -4]]
a = np.matrix(a)
print(a, np.shape(a))

#обратный степенной метод

chisl = []
vect = []
for d in range(1, 101):
	delta0 = d
	delta1 = 0
	eps = pow(10, -4)
	y0 = []
	for i in range(n):
		y0.append(random.randint(1, 101))
	norm = np.linalg.norm(y0)
	z0 = []
	m = [0] * n
	m1 = [0] * n
	for i in y0:
		z0.append(i / norm)
	while True:
		ytec = np.dot(np.linalg.inv(a - np.identity(n) * delta0), z0)
		normtec = np.linalg.norm(ytec)
		ztec = []
		for i in ytec:
			ztec.append(i / normtec)
		for i in range(n):
			if abs(ytec[i]) > 0:
				m[i] = z0[i] / ytec[i]
			else:
				m[i] = m1[i]
		dop = 0
		k = 0
		for i in range(n):
			if m[i] != m1[i]:
				dop += m[i]
				k += 1
		dop /= k
		delta1 = delta0 + dop
		z0 = ztec.copy()
		if abs(delta1 - delta0) < eps:
			break
		delta0 = delta1
	flag = True
	for i in chisl:
		if abs(i - delta1) < pow(10, -3):
			flag = False
	if flag:
		chisl.append(delta1)
		vect.append(z0)
print('--------------------------')
for i in range(len(chisl)):
	print(chisl[i])
	print(*vect[i])
	print(*np.dot(a, vect[i]) / chisl[i])
	print('--------------------------')



[[79, 0, 0], [0, 82, 0], [0, 0, 32]]
[[ 13.89856807 -20.24033565 -17.61415879]
 [ 74.66771727  99.56083596  16.71828227]
 [-17.82911068  -1.45729424  79.54059597]]
[[ 1 -2 -2]
 [ 1  4  2]
 [ 0 -6 -4]] (3, 3)


ValueError: ignored

In [ ]:
print()

[[1 4 2]]
